export default [
    {   id: "1",
        title : "ilmu padi abangkuhh🌾🌾👊🏻💥🔥",
        description : "lmu padi abangkuhh🌾🌾👊🏻💥🔥",
        date: "Sabtu, 13 jan 2024",
        tags1: "Getting Started ",
    },
    {   id: "2",
        link : "/Blog/toolsui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/toolsui.webp",
        title : "weees kelas abangku 🔥🔥",
        description : "weees kelas abangku 🔥🔥",
        date: "Senin, 15 jan 2024",
        tags1: "tailwind css",
        tags2: "ui components",
        
    },
    {   id: "3",
        link : "/Blog/loadimage",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "kelas boskuuuh 🔥👍🏼",
        description : "kelas boskuuuh 🔥👍🏼",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
   
    {   id: "4",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "ini mahkotamu king 👑",
        description : "ini mahkotamu king 👑",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "5",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "eihhh mantaapp pedii kaliii 🔥🔥🔥",
        description : "eihhh mantaapp pedii kaliii 🔥🔥🔥",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "6",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "terbaik kandaku 🙌🏼",
        description : "terbaik kandaku 🙌🏼",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "7",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "manyala capt 🔥🔥",
        description : "manyala capt 🔥🔥",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "8",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "sungkem dulu abangkuuu🙇‍♂️🙇‍♂️",
        description : "sungkem dulu abangkuuu🙇‍♂️🙇‍♂️",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
   
    {   id: "9",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "nyalain sendiri 🔥🔥🔥 ",
        description : "nyalain Sendiri 🔥🔥🔥",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "10",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "capt idolaa 🔥🙌🏼🔝 ",
        description : "capt idolaa 🔥🙌🏼🔝",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "11",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "top selalu idola 🔥",
        description : "top selalu idola 🔥",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "12",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "jangan kasih kendor king 🔥🔥🔥",
        description : "jangan kasih kendor king 🔥🔥🔥",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "13",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "ini mahkotamu king 👑",
        description : "ini mahkotamu king 👑",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "14",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "tetep ilmu padi 🌾🌾",
        description : "tetep ilmu padi 🌾🌾",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "15",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "menyala abangkuhh 🔥🔥🔥",
        description : "menyala abangkuhh 🔥🔥🔥",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "16",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "kasi paham wakk 🔥🔥🔥",
        description : "kasi paham wakk 🔥🔥🔥",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "17",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "kasih keras abangkuhh 🔥👊🏼",
        description : "kasih keras abangkuhh 🔥👊🏼",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "18",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "lanjutkan abangkuuhh 🔥🔝💥",
        description : "lanjutkan abangkuuhh 🔥🔝💥",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "19",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "sehat selalu kaka panutan 💪💪✋",
        description : "sehat selalu kaka panutan 💪💪✋",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "20",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "apotik tutup captain 🔥🔥💯🔝",
        description : "apotik tutup captain 🔥🔥💯🔝",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
   
    {   id: "21",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "sesekali 🙌🏼",
        description : "sesekali 🙌🏼",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "21",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "tipis tipis asal menyala king 👑🔥",
        description : "tipis tipis asal menyala king 👑🔥",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "22",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "percaya proses king 💯💯💪❤‍🔥",
        description : "percaya proses king 💯💯💪❤‍🔥",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "23",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "kasih apa? kasih paham abangkuhh👊👊👊🔥🔥🔥🔥",
        description : "kasih apa? kasih paham abangkuhh👊👊👊🔥🔥🔥🔥",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "24",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "meroket abangku 🚀🚀🚀",
        description : "meroket abangku 🚀🚀🚀",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "25",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "kasih paham queen, ilmu baddie 🔥🔥💅💅",
        description : "kasih paham queen, ilmu baddie 🔥🔥💅💅",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "26",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "kasih paham queen 🤭🔥 MENYALA",
        description : "kasih paham queen 🤭🔥 MENYALA",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "26",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.webp",
        title : "tetep ilmu padi 🌾🌾",
        description : "tetep ilmu padi 🌾🌾",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
   
]